# Generated by Django 4.1.5 on 2023-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkApp', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to='message_pictures/'),
        ),
    ]
